import { IProduct } from "./products.model";

export const products: IProduct[] = [
    {
    image: "./ex3-images/backpack.jpg",
    title: "AMAZING Backpack - Your Best Companion",
    type: "Hiking-backpack",
    description: "30L. Hiking Backpack for all your troubles. Never leave anything behind with 7 different compartments and 5 hidden pockets your items will be safe as a baby kangaroo nested in her mother's belly. Fully Waterproof and indestructable to take with you on any adventure.",
    qtty: 1,
    price: 35,
    availability: true,
},
{
    image: "./ex3-images/bicycle.jpg",
    title: "WonderBike - Take me to Places",
    type: "Gliding-Bike",
    description: "Full Aluminium Body will never see any trace of rust. This bike will be your companion through your whole life and generations to come. 28 Gears provide you with enough options for any kind of steepy sloopy road, even the hilly-billy streets of San Francisco will feel like you are just rollin' your way downtown on a perfectly even road. Sell your car today, HELP THE ENVIRONMENT and buy this bike, help us save the planet and exercise anytime you want to go somewhere.",
    qtty: 1,
    price: 2500,
    availability: true,
},
{
    image: "./ex3-images/canoe.jpg",
    title: "MID-LIFE Crisis represents - The Canoe that will cure all your problems",
    type: "Mid-Life-Crisis Canoe",
    description: "First you tried cycling, but you still feel depressed somehow. It is time to buy the next absolutely unnecessary item to help you find yourself again in the middle of your life with another absolutely unnecessary hobby that you will maybe think about doing once every three years. Enough said, this canoe will look wonderful in your garage collecting all the dust - untouched for the upcoming years!",
    qtty: 1,
    price: 800,
    availability: true,
},
{
    image: "./ex3-images/fishing-set.jpg",
    title: "GET-AWAY from Family - Fishing SET",
    type: "Fishing Set",
    description: "Have you had enough of Family-Time and been looking for that quality time doing absolutely nothing while absolutely nobody is disturbing you? With this fishing set you have just found the perfect excuse to practice the most boring hobby you could possibly ever find to do which is only acceptable to practice if you have the CPU of  an 80 year old. Get this fishing set, and off to the middle of nowhere where nobody can disturb you to finally have a relaxing time, doing your favourite thing in the world - absolutely nothing.",
    qtty: 1,
    price: 200,
    availability: true,
},
{
    image: "./ex3-images/grill.jpg",
    title: "Grill",
    type: "Grill",
    description: "This is maybe the only item you might actually need or use in the whole list.",
    qtty: 1,
    price: 115,
    availability: false,
},
{
    image: "./ex3-images/raincoat.jpg",
    title: "Raincoat",
    type: "Coat for Rain",
    description: "Nothing special about this one, don't wear short-sleeves you will sweat and the coat will keep sticking to your arms",
    qtty: 1,
    price: 25,
    availability: false,
},
{
    image: "./ex3-images/shoes.jpg",
    title: "DORA the Explorer - Hiking Shoes",
    type: "Merch",
    description: "This is the original model that Dora the explorer used in her adventures, and we all know she is nowhere to joke around when it comes to being a complete narcissist who only serves herself the best of things.",
    qtty: 1,
    price: 350,
    availability: true,
},
{
    image: "./ex3-images/tent.jpg",
    title: "TENT to be hot here",
    type: "Portable Sauna",
    description: "Who doesn't like a good nylon enclosure where you can roll around all night long getting no sleep whatsoever for the next day which you will scratching all the mosquito bites you have from the wonderful idea of going camping in the nature? Take this tent to remind yourself how nice and luxurious it is to have an apartment with air conditioning and fridge whenever you feel like you are becoming a bit too spoiled and take everything for granted.",
    qtty: 1,
    price: 450,
    availability: true,
},
{
    image: "./ex3-images/trailer.jpg",
    title: "Affordable apartment",
    type: "Real Estate in 2024",
    description: "You and your spouse both have fair amounts of income working both full time with extra plus hours? Well it is time to invest in your first real estate and start owning something in 2024. Take this trailer and invest in real estate now, and don't regret it in 30 years when trailers come only with subscriptions!",
    qtty: 1,
    price: 285000,
    availability: true,
},
]